name: fzkt_openstreet
description: "ride app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase & Google
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_sign_in: ^6.2.1

  # State Management & Services
  provider: ^6.1.2
  flutter_dotenv: ^6.0.0
  intl: ^0.20.2
  
  # Supabase
  supabase_flutter: ^2.0.0

  # Other dependencies
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.1
  http: ^1.2.2
  go_router: ^14.0.0
  google_fonts: ^6.3.3
  
  # Maps
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  
  # Web
  web: ^1.1.1
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # PDF Generation and Printing
  pdf: ^3.11.1
  printing: ^5.13.2
  
  # URL Launcher
  url_launcher: ^6.3.2
  
  # Social Icons
  font_awesome_flutter: ^10.7.0
  dtd: ^4.0.0
  flutter_lints: ^6.0.0
  json_rpc_2: ^4.0.0
  path: ^1.9.1
  stack_trace: ^1.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - env
    - assets/images/
    - assets/images/logo_21.png
    - assets/images/cars/economica.jpg
    - assets/images/cars/sedan.jpg
    - assets/images/cars/suv.jpg
    - assets/images/cars/van.jpg
    - assets/images/cars/luxury.jpg
    - assets/images/cars/flote.png
    - assets/images/background/bg_1.jpg
    - assets/images/background/bg_2.jpg
    - assets/images/background/bg_3.jpg
    - assets/images/background/bg_4.jpg
    - assets/images/background/bg_5.jpg
    - assets/images/background/bg_6.jpg
    - assets/images/background/bg_7.jpg
    - assets/images/empresa/city.jpg
    - assets/images/empresa/oficina.png
    - assets/images/empresa/pared.png
    - assets/images/empresa/driver.png
    - assets/images/destinos/destination_1.jpg
    - assets/images/destinos/destination_2.jpg
    - assets/images/destinos/destination_3.jpg
    - assets/images/destinos/destination_4.jpg
    - assets/images/destinos/destination_5.jpg
    - assets/images/destinos/bergamo.png
    - assets/images/destinos/catania.png
    - assets/images/destinos/linate.jpg
    - assets/images/destinos/palermo.png
    - assets/images/destinos/torino.png
    - lib/l10n/es.json
    - lib/l10n/en.json
    - lib/l10n/it.json
    - lib/l10n/de.json
    - assets/data/common_places.json
    - assets/data/predefined_routes.json